modLoader="javafml" #mandatory
loaderVersion="[36,)" #mandatory
license="GNU Lesser General Public License v3.0"
issueTrackerURL="https://github.com/Darkorg69/SereneSeasonsPHC2/issues" #optional

[[mods]] #mandatory
modId="sereneseasonsphc2" #mandatory
version="1.16.5-1.0.0" #mandatory
displayName="Serene Seasons PamHC2 Compat" #mandatory
#updateJSONURL="https://github.com/Darkorg69" #optional
displayURL="https://github.com/Darkorg69/SereneSeasonsPHC2" #optional
logoFile="sereneseasonsphc2.png" #optional
credits="Java and the Forge team for making this mod possible!" #optional
authors="Darkorg" #optional
description='''This mod adds seasonal tags to all Pam's Harvest Craft 2: Crops, so they can grow in their respective seasons.'''

[[dependencies.sereneseasonsphc2]] #optional
modId="forge" #mandatory
mandatory=true #mandatory
versionRange="[36,)" #mandatory
ordering="NONE"
side="BOTH"
[[dependencies.sereneseasonsphc2]]
modId="minecraft"
mandatory=true
versionRange="[1.16.5]"
ordering="NONE"
side="BOTH"
